name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: yourpassword
          MYSQL_DATABASE: animemap
        ports:
          - '3306:3306'

    steps:
    - uses: actions/checkout@v2

    - name: List root directory contents
      run: ls -la

    - name: List frontend directory contents
      run: ls -la ./frontend

    - name: List backend directory contents
      run: ls -la ./backend

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install frontend dependencies
      working-directory: ./frontend
      run: npm install

    - name: Install backend dependencies
      working-directory: ./backend
      run: npm install

    - name: Run frontend tests
      working-directory: ./frontend
      run: npm test

    - name: Run backend tests
      working-directory: ./backend
      run: npm test
