name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: yourpassword
          MYSQL_DATABASE: animemap
        ports:
          - '3306:3306'

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        cd frontend && npm install
        cd ../backend && npm install

    - name: Run tests
      run: |
        cd frontend && npm test
        cd ../backend && npm test
